import "./globals.css";
import localFont from 'next/font/local';


const GESS = localFont({
  src: [
    {
      path: '../../public/fonts/GE SS Unique/GE SS Unique Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GE SS Unique/GE SS Unique Light.otf',
      weight: '400',
      style: 'normal',
    },
    
  ],
  variable: '--font-GESS',
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GESS.variable}`}>
      <head>
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&family=Kufam:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet" />
      </head>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
