import "./globals.css";
import localFont from 'next/font/local';

const kufam = localFont({
  src: [
    {
      path: '../../public/fonts/Kufam/ArbFONTS-kufam-regular-webfont.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Kufam/ArbFONTS-Kufam Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Kufam/ArbFONTS-Kufam-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
  ],
  variable: '--font-kufam',
});

const GESS = localFont({
  src: [
    {
      path: '../../public/fonts/GE SS Unique/GE SS Unique Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GE SS Unique/GE SS Unique Light.otf',
      weight: '400',
      style: 'normal',
    },
    
  ],
  variable: '--font-GESS',
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${kufam.variable} ${GESS.variable}`}>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
